# 配置文件
# 需要哪些配置看conf/config.go
##################################

# JWT配置
[JwtSecret]
Rest = "XG7t63VfqKu8MoWH"
Admin = "XG7t63VfqKu8MoWH"

# 日志配置
[Logger]
Level = "debug"
Target = "console"
Filename = "./log/stream.log"

[RestServer]
Addr = "0.0.0.0:8000"

[AdminServer]
Addr = "127.0.0.1:8001"

# 数据库配置
[DataSource]
DSN = "host=localhost user=postgres password=password dbname=ai_chat port=5432 sslmode=disable"
MaxIdle = 20
MaxOpen = 100
MaxLifetime = 600
Migrate = true
LogDisabled = true

# Redis配置
[Redis]
Addr = "127.0.0.1:6379"
Password = ""
DB = 0
